export const SPORT_ICONS: { [key: number]: { icon: string; name: string } } = {
  1: { icon: 'sports_baseball', name: 'Baseball' },
  2: { icon: 'sports_basketball', name: 'Basketball' },
  4: { icon: 'sports_soccer', name: 'Futsal' },
  5: { icon: 'sports_handball', name: 'Handball' },
  6: { icon: 'sports_hockey', name: 'Hockey' },
  7: { icon: 'sports_soccer', name: 'Soccer' },
  8: { icon: 'sports_tennis', name: 'Tennis' },
  9: { icon: 'sports_volleyball', name: 'Volleyball' },
  10: { icon: 'sports_football', name: 'American Football' },
  11: { icon: 'sports', name: 'Snooker' },
  12: { icon: 'sports', name: 'Darts' },
  13: { icon: 'sports_tennis', name: 'Table Tennis' },
  14: { icon: 'sports_tennis', name: 'Badminton' },
  15: { icon: 'sports_rugby', name: 'Rugby League' },
  16: { icon: 'pool', name: 'Water Polo' },
  17: { icon: 'sports_hockey', name: 'Bandy' },
  18: { icon: 'sports_martial_arts', name: 'Martial arts' },
  19: { icon: 'sports_hockey', name: 'Field Hockey' },
  20: { icon: 'sports_football', name: 'AFL' },
  21: { icon: 'sports_esports', name: 'Other E-Sports' },
  22: { icon: 'extension', name: 'Chess' },
  23: { icon: 'sports', name: 'Gaelic Sport' },
  24: { icon: 'sports_cricket', name: 'Cricket' },
  25: { icon: 'sports_motorsports', name: 'Formula 1' },
  27: { icon: 'sports_motorsports', name: 'Motorsport' },
  28: { icon: 'directions_bike', name: 'Cycling' },
  29: { icon: 'sports_volleyball', name: 'Beach Volleyball' },
  30: { icon: 'pets', name: 'Horse Racing' },
  31: { icon: 'sports', name: 'Biathlon' },
  32: { icon: 'sports', name: 'Curling' },
  33: { icon: 'sports_tennis', name: 'Squash' },
  34: { icon: 'sports_basketball', name: 'Netball' },
  35: { icon: 'sports_soccer', name: 'Beach Soccer' },
  36: { icon: 'sports_hockey', name: 'Floorball' },
  37: { icon: 'sports', name: 'Hurling' },
  38: { icon: 'sports_volleyball', name: 'Kung Volleyball' },
  39: { icon: 'sports_esports', name: 'E-Soccer' },
  41: { icon: 'sports_esports', name: 'E-Basketball' },
  43: { icon: 'sports_rugby', name: 'Rugby Union' },
  44: { icon: 'sports_mma', name: 'Boxing' },
  45: { icon: 'sports_mma', name: 'MMA' },
  46: { icon: 'sports_esports', name: 'Dota 2' },
  47: { icon: 'sports_esports', name: 'Counter-Strike' },
  48: { icon: 'sports_esports', name: 'League of Legends' },
  49: { icon: 'sports_golf', name: 'Golf' },
  50: { icon: 'sports', name: 'Lacrosse' },
  51: { icon: 'sports_esports', name: 'Valorant' },
  52: { icon: 'sports_esports', name: 'Overwatch' },
  53: { icon: 'sports_esports', name: 'PUBG' },
  54: { icon: 'sports_esports', name: 'Fortnite' },
  55: { icon: 'sports_esports', name: 'Rainbow Six' },
  56: { icon: 'sports_esports', name: 'Cross Fire' },
  57: { icon: 'sports_esports', name: 'Call of Duty' },
  58: { icon: 'sports_esports', name: 'Apex Legends' },
  59: { icon: 'sports_esports', name: 'Deadlock' },
  60: { icon: 'sports_esports', name: 'Standoff 2' },
  61: { icon: 'sports_esports', name: 'King of Glory' },
  62: { icon: 'sports_esports', name: 'Arena of Valor' },
  63: { icon: 'sports_esports', name: 'Mobile Legends' },
  64: { icon: 'sports_esports', name: 'Heroes of the Storm' },
  65: { icon: 'sports_esports', name: 'StarCraft' },
  66: { icon: 'sports_esports', name: 'Warcraft' },
  67: { icon: 'sports_esports', name: 'Age of Empires' },
  68: { icon: 'sports_esports', name: 'Hearthstone' },
  69: { icon: 'sports_esports', name: 'Rocket League' },
  70: { icon: 'sports_esports', name: 'Brawl Stars' },
  71: { icon: 'sports_esports', name: 'HALO' }
};

export function getSportIcon(sportId: number): string {
  return SPORT_ICONS[sportId]?.icon || 'emoji_events';
}

export function getSportName(sportId: number): string {
  return SPORT_ICONS[sportId]?.name || 'Unknown Sport';
}
